# Generated by Django 6.0.2 on 2026-03-02 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='university',
            field=models.CharField(max_length=200, verbose_name='Вуз'),
        ),
    ]
